//
// ResultList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ResultList: Codable {

    public var results: [Result]?

    public init(results: [Result]?) {
        self.results = results
    }


}

